/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#111317",
        "on-secondary-container": "#d6a9ff",
        "on-primary-fixed": "#231b00",
        "secondary-container": "#6f00be",
        "on-secondary-fixed": "#2c0051",
        "bg-secondary": "#181B22",
        "primary-fixed-dim": "#ecc200",
        "outline-variant": "#4d4632",
        "outline": "#999077",
        "on-primary-fixed-variant": "#564500",
        "background": "#111317",
        "tertiary-fixed": "#88f3ff",
        "on-tertiary-fixed-variant": "#004f56",
        "bg-surface": "#242932",
        "inverse-primary": "#725c00",
        "on-surface": "#e2e2e8",
        "surface-container-high": "#282a2e",
        "status-warning": "#F59E0B",
        "tertiary-fixed-dim": "#00dbec",
        "tertiary-container": "#00ecfe",
        "status-offline": "#64748B",
        "surface-tint": "#ecc200",
        "primary-container": "#ffd200",
        "on-secondary-fixed-variant": "#6900b3",
        "inverse-on-surface": "#2f3035",
        "on-tertiary-fixed": "#001f23",
        "surface": "#111317",
        "on-secondary": "#490080",
        "border-subtle": "#334155",
        "on-tertiary-container": "#00676f",
        "surface-variant": "#333539",
        "on-primary": "#3b2f00",
        "primary-fixed": "#ffe07c",
        "on-primary-container": "#705b00",
        "surface-container-highest": "#333539",
        "status-critical": "#EF4444",
        "on-error-container": "#ffdad6",
        "tertiary": "#d1faff",
        "secondary-fixed-dim": "#ddb7ff",
        "surface-container": "#1e2024",
        "error": "#ffb4ab",
        "status-healthy": "#22C55E",
        "surface-bright": "#37393e",
        "on-error": "#690005",
        "on-tertiary": "#00363b",
        "inverse-surface": "#e2e2e8",
        "on-surface-variant": "#d1c6ab",
        "secondary-fixed": "#f0dbff",
        "secondary": "#ddb7ff",
        "error-container": "#93000a",
        "surface-container-lowest": "#0c0e12",
        "surface-container-low": "#1a1c20",
        "primary": "#fff2d1",
        "on-background": "#e2e2e8"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Hanken Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        "sensor-lg": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "title-lg": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "headline-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "sensor-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "title-lg": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}]
      },
      borderRadius: {
        'lg': '16px',
        'md': '8px',
        'full': '9999px',
      },
      spacing: {
        '24': '24px',
        "stack-md": "16px",
        "stack-sm": "8px",
        "sidebar-width": "280px",
        "grid-margin": "24px",
        "gutter": "24px",
        "stack-lg": "24px"
      }
    },
  },
  plugins: [],
}
