version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: djezzy_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: djezzy_ssop
    ports:
      - "5432:5432"
    volumes:
      - djezzy_postgres_data:/var/lib/postgresql/data

volumes:
  djezzy_postgres_data:
